# Generated by Django 3.2.8 on 2021-10-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='serv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('M', 'Maquillaje'), ('TC', 'Tratamientos Corporales'), ('TF', 'Tratamientos Faciales'), ('E', 'Especial')], max_length=50)),
                ('precio', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loanapp.persona')),
            ],
        ),
    ]
