# Generated by Django 3.2.8 on 2021-10-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_serv', models.CharField(max_length=50)),
            ],
        ),
    ]
