# Generated by Django 3.2.8 on 2021-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cita',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.RemoveField(
            model_name='serv',
            name='fecha',
        ),
        migrations.AddField(
            model_name='serv',
            name='precio',
            field=models.FloatField(default=None),
        ),
    ]
