# Generated by Django 3.2.8 on 2021-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=20)),
                ('contraseña', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='serv',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='persona',
            name='contraseña',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
